cookie:
  expiry_days: 30
  key: careflow_secret_key_2026
  name: careflow_auth_cookie
credentials:
  usernames:
    admin:
      email: admin@careflow.ai
      name: System Administrator
      password: $2b$12$haCQtGDjnN43fxeRaOqphe498r4dKHj2THiY.loFd0ed5wVF6flJ.
    doctor:
      email: doctor@careflow.ai
      name: Medical Professional
      password: $2b$12$X.Yi1.5JMlPPYgPvDbOrUO6371llJdh5EW2FnwbnxrpHV9rqyoNUu
pre-authorized:
  emails:
  - admin@careflow.ai
